name: miri tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  miri:
    name: "miri"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@nightly
      with:
        components: miri
    
    - name: Setup Miri
      run: cargo miri setup
    
    - name: Run Miri Tests
      run: cargo miri test
      env:
        MIRIFLAGS: -Zmiri-strict-provenance
